services:
  chat-api:
    build: ./chat-api
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./chat-api/src:/app/src
      - ./chat-api/pom.xml:/app/pom.xml
    env_file:
      - ./chat-api/.env

  chat-spa:
    build: ./chat-spa
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

